# Generated by Django 4.1 on 2022-08-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavra',
            name='sinal',
            field=models.ImageField(upload_to=None),
        ),
    ]
