# Generated by Django 4.1 on 2022-09-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_palavra_sinal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palavra',
            name='sinal',
        ),
    ]
