# Generated by Django 4.1 on 2022-09-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_palavra_sinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='palavra',
            name='sinal',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
